services:
  - type: web
    name: telegram-userbot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: DATABASE_PATH
        value: /data/userbot.db
    disk:
      name: data
      mountPath: /data
